### ISSUE TITLE
Copy selector or lock highlight?

### ISSUE THREAD

**Issue by nathgit** [CharltonC/chrome-css-selector-highlight#3]
Is there any chance of a shortcut being added to either copy selector or to lock highlight? It's difficult to copy a selector when moving the mouse highlights a different selector.

**Comment by CharltonC** [comment]
> Is there any chance of a shortcut being added to either copy selector or to lock highlight? It's difficult to copy a selector when moving the mouse highlights a different selector.

Use the control key to lock (toggle) the highlight. Hope that helps. Cheers.

Reference: https://github.com/CharltonC/chrome-css-selector-capture#shortcut-hotkeys-only-when-app-is-enabled

**Comment by CharltonC** [comment]
@nathgit I assume the response above should solve your query. I will close this issue for now. Feel free to let me know if there is any other question. Cheers.
